#!/bin/bash

# export PETSC_DIR=${PWD}/../../lib/petsc-3.3-p5 
# export SLEPC_DIR=${PWD}/../../lib/slepc-3.3-p3
# export PETSC_ARCH=aa-aa


cp ./rschr/Makefile ../../src/

cd ../../src/

make clean
make -j2

